### ISSUE TITLE
MIT License Request

### ISSUE THREAD

**Issue by ivannikitovic** [anon767/maangcrawler#1]
Hi Tom,

Fantastic project! The job market has been rough in the past year or so and I found your repository extremely helpful. However, I noticed that you did not upload a license so I was unsure whether I could use your code for some of my projects. I kindly ask you to upload a license to this project, preferably MIT, so that I can at least use it for inspiration since I am having difficulty navigating the network requests and you figured it out perfectly. Feel free to check out my GitHub profile and reach out to me on LinkedIn!

Thank you.

**Comment by anon767** [comment]
Alright done! :)
